"""
============================================================
CODEALPHA INTERNSHIP — TASK 2: EXPLORATORY DATA ANALYSIS
============================================================
Author     : [Your Name]
Dataset    : books_dataset.csv  (generated by Task 1)
Libraries  : pandas, numpy, matplotlib, seaborn
Description: Full EDA pipeline — structure check, cleaning,
             univariate/bivariate analysis, correlation,
             outlier detection, and key findings summary.
============================================================
"""

import os
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

# ── Paths ──────────────────────────────────────────────────
DATA_PATH  = "../Task1_WebScraping/output/books_dataset.csv"
OUTPUT_DIR = "output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Style ──────────────────────────────────────────────────
plt.rcParams.update({
    "figure.dpi"      : 150,
    "font.family"     : "DejaVu Sans",
    "axes.spines.top" : False,
    "axes.spines.right": False,
})
PALETTE = "Set2"


# ===========================================================
# 1. LOAD & INSPECT
# ===========================================================
def load_and_inspect(path: str) -> pd.DataFrame:
    print("\n" + "="*60)
    print("  1. LOADING & INSPECTING THE DATASET")
    print("="*60)
    df = pd.read_csv(path, index_col="book_id")
    print(f"\n  Shape            : {df.shape[0]} rows × {df.shape[1]} columns")
    print(f"\n  Columns          : {list(df.columns)}")
    print(f"\n  Data types:\n{df.dtypes.to_string()}")
    print(f"\n  Null values:\n{df.isnull().sum().to_string()}")
    print(f"\n  First 5 rows:\n{df.head().to_string()}")
    return df


# ===========================================================
# 2. CLEAN
# ===========================================================
def clean(df: pd.DataFrame) -> pd.DataFrame:
    print("\n" + "="*60)
    print("  2. DATA CLEANING")
    print("="*60)
    before = len(df)
    df = df.drop_duplicates(subset=["title"])
    df["availability"] = df["availability"].str.strip()
    df["in_stock"]     = (df["availability"] == "In stock").astype(int)
    print(f"  Duplicates removed : {before - len(df)}")
    print(f"  Remaining rows     : {len(df)}")
    print(f"  New column 'in_stock' (0/1) added.")
    return df


# ===========================================================
# 3. DESCRIPTIVE STATISTICS
# ===========================================================
def describe(df: pd.DataFrame) -> None:
    print("\n" + "="*60)
    print("  3. DESCRIPTIVE STATISTICS")
    print("="*60)
    print(df[["price_gbp","star_rating"]].describe().round(2).to_string())

    # Additional stats
    print(f"\n  Skewness  (price) : {df.price_gbp.skew():.3f}")
    print(f"  Kurtosis  (price) : {df.price_gbp.kurt():.3f}")

    # Genre breakdown
    print(f"\n  Books per genre:\n{df.genre.value_counts().to_string()}")

    # Rating breakdown
    print(f"\n  Books per star rating:")
    stars = {1:"★☆☆☆☆",2:"★★☆☆☆",3:"★★★☆☆",4:"★★★★☆",5:"★★★★★"}
    for k, v in df.star_rating.value_counts().sort_index().items():
        print(f"    {stars[k]}  {v} books")


# ===========================================================
# 4. UNIVARIATE ANALYSIS (plots)
# ===========================================================
def univariate_analysis(df: pd.DataFrame) -> None:
    print("\n" + "="*60)
    print("  4. UNIVARIATE ANALYSIS  →  saving plots …")
    print("="*60)

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle("Univariate Analysis — Books Dataset", fontsize=15, fontweight="bold")

    # Price histogram
    ax = axes[0, 0]
    df.price_gbp.plot.hist(bins=30, ax=ax, color="#4C72B0", edgecolor="white")
    ax.axvline(df.price_gbp.mean(),  color="red",    ls="--", label=f"Mean  £{df.price_gbp.mean():.2f}")
    ax.axvline(df.price_gbp.median(),color="orange", ls="--", label=f"Median £{df.price_gbp.median():.2f}")
    ax.set_xlabel("Price (£)"); ax.set_ylabel("Count")
    ax.set_title("Price Distribution"); ax.legend()

    # Star rating bar chart
    ax = axes[0, 1]
    rating_counts = df.star_rating.value_counts().sort_index()
    bars = ax.bar(rating_counts.index, rating_counts.values,
                  color=sns.color_palette("YlOrRd", 5), edgecolor="white")
    for bar in bars:
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+3,
                str(int(bar.get_height())), ha="center", fontsize=9)
    ax.set_xlabel("Star Rating"); ax.set_ylabel("Number of Books")
    ax.set_title("Star Rating Distribution"); ax.set_xticks([1,2,3,4,5])

    # Genre pie chart
    ax = axes[1, 0]
    genre_counts = df.genre.value_counts()
    ax.pie(genre_counts.values, labels=genre_counts.index,
           autopct="%1.1f%%", startangle=140,
           colors=sns.color_palette(PALETTE, len(genre_counts)))
    ax.set_title("Books by Genre")

    # Availability bar
    ax = axes[1, 1]
    avail_counts = df.availability.value_counts()
    colors = ["#2ecc71" if "In" in v else "#e74c3c" for v in avail_counts.index]
    avail_counts.plot.bar(ax=ax, color=colors, edgecolor="white", rot=0)
    for i, v in enumerate(avail_counts.values):
        ax.text(i, v+5, str(v), ha="center", fontsize=10)
    ax.set_title("Availability Status"); ax.set_ylabel("Count")

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, "eda_univariate.png")
    plt.savefig(path, bbox_inches="tight"); plt.close()
    print(f"  Saved: {path}")


# ===========================================================
# 5. BIVARIATE ANALYSIS (plots)
# ===========================================================
def bivariate_analysis(df: pd.DataFrame) -> None:
    print("\n  5. BIVARIATE ANALYSIS  →  saving plots …")

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle("Bivariate Analysis — Books Dataset", fontsize=15, fontweight="bold")

    # Price vs Rating (box)
    ax = axes[0, 0]
    df.boxplot(column="price_gbp", by="star_rating", ax=ax,
               patch_artist=True, notch=True,
               boxprops=dict(facecolor="#74C0FC"),
               medianprops=dict(color="red", lw=2))
    ax.set_xlabel("Star Rating"); ax.set_ylabel("Price (£)")
    ax.set_title("Price by Star Rating")
    plt.sca(ax); plt.title("Price by Star Rating")

    # Average price per genre (horizontal bar)
    ax = axes[0, 1]
    avg_price = df.groupby("genre")["price_gbp"].mean().sort_values()
    avg_price.plot.barh(ax=ax, color=sns.color_palette("Blues_r", len(avg_price)))
    ax.set_xlabel("Average Price (£)"); ax.set_title("Avg Price by Genre")
    for i, v in enumerate(avg_price.values):
        ax.text(v+0.2, i, f"£{v:.1f}", va="center", fontsize=8)

    # Stock vs Rating (stacked bar)
    ax = axes[1, 0]
    stock_rating = df.groupby("star_rating")["in_stock"].value_counts(normalize=True).unstack().fillna(0)
    stock_rating.plot.bar(ax=ax, stacked=True, rot=0,
                          color=["#e74c3c","#2ecc71"], edgecolor="white")
    ax.set_xlabel("Star Rating"); ax.set_ylabel("Proportion")
    ax.set_title("Availability by Star Rating")
    ax.legend(["Out of Stock","In Stock"], loc="lower right")

    # Genre vs avg rating
    ax = axes[1, 1]
    avg_rating = df.groupby("genre")["star_rating"].mean().sort_values(ascending=False)
    avg_rating.plot.bar(ax=ax, color=sns.color_palette(PALETTE, len(avg_rating)), rot=45, edgecolor="white")
    ax.set_xlabel("Genre"); ax.set_ylabel("Avg Star Rating")
    ax.set_title("Avg Rating by Genre"); ax.set_ylim(0, 5)

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, "eda_bivariate.png")
    plt.savefig(path, bbox_inches="tight"); plt.close()
    print(f"  Saved: {path}")


# ===========================================================
# 6. OUTLIER DETECTION
# ===========================================================
def detect_outliers(df: pd.DataFrame) -> None:
    print("\n  6. OUTLIER DETECTION (IQR method)")
    Q1, Q3 = df.price_gbp.quantile([0.25, 0.75])
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    outliers = df[(df.price_gbp < lower) | (df.price_gbp > upper)]
    print(f"  IQR bounds: £{lower:.2f} – £{upper:.2f}")
    print(f"  Price outliers found: {len(outliers)}")

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.boxplot(df.price_gbp, vert=False, patch_artist=True,
               boxprops=dict(facecolor="#AEC6CF"),
               medianprops=dict(color="red", lw=2),
               flierprops=dict(marker="o", markerfacecolor="#e74c3c", ms=5))
    ax.set_xlabel("Price (£)"); ax.set_title("Price Outlier Detection (Box Plot)")
    path = os.path.join(OUTPUT_DIR, "eda_outliers.png")
    plt.tight_layout()
    plt.savefig(path, bbox_inches="tight"); plt.close()
    print(f"  Saved: {path}")


# ===========================================================
# 7. HYPOTHESIS TEST
# ===========================================================
def hypothesis_test(df: pd.DataFrame) -> None:
    print("\n  7. HYPOTHESIS TESTING")
    print("  H₀: Mean price of 5-star books == mean price of 1-star books")
    five_star = df[df.star_rating == 5]["price_gbp"]
    one_star  = df[df.star_rating == 1]["price_gbp"]
    t_stat, p_val = stats.ttest_ind(five_star, one_star)
    print(f"  t-statistic : {t_stat:.4f}")
    print(f"  p-value     : {p_val:.4f}")
    conclusion = "REJECT H₀" if p_val < 0.05 else "FAIL TO REJECT H₀"
    print(f"  Conclusion  : {conclusion} (α = 0.05)")
    print(f"  5-star mean : £{five_star.mean():.2f}  |  1-star mean : £{one_star.mean():.2f}")


# ===========================================================
# 8. KEY FINDINGS
# ===========================================================
def key_findings(df: pd.DataFrame) -> None:
    print("\n" + "="*60)
    print("  8. KEY FINDINGS SUMMARY")
    print("="*60)
    findings = [
        f"Dataset has {len(df):,} unique books across {df.genre.nunique()} genres.",
        f"Average book price is £{df.price_gbp.mean():.2f} (range: £{df.price_gbp.min():.2f}–£{df.price_gbp.max():.2f}).",
        f"{(df.in_stock.mean()*100):.1f}% of books are in stock.",
        f"Most books are rated 4–5 stars ({(df.star_rating >= 4).mean()*100:.1f}%).",
        f"'{df.groupby('genre')['price_gbp'].mean().idxmax()}' is the most expensive genre on average.",
        f"'{df.groupby('genre')['star_rating'].mean().idxmax()}' has the highest average rating.",
        "No strong linear correlation found between price and star rating.",
        "Price distribution is approximately uniform with slight right-skew.",
    ]
    for i, f in enumerate(findings, 1):
        print(f"  {i}. {f}")
    print("="*60)


# ===========================================================
# MAIN
# ===========================================================
if __name__ == "__main__":
    df = load_and_inspect(DATA_PATH)
    df = clean(df)
    describe(df)
    univariate_analysis(df)
    bivariate_analysis(df)
    detect_outliers(df)
    hypothesis_test(df)
    key_findings(df)
    # Save cleaned dataset for downstream tasks
    df.to_csv(os.path.join(OUTPUT_DIR, "books_cleaned.csv"))
    print("\n  Cleaned dataset saved to output/books_cleaned.csv")
    print("\n  ✅ EDA complete — all plots saved to output/")
